apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-practice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ramwissen/k8s-practice.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
