apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-practice
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ramwissen/k8s-practice.git
    targetRevision: HEAD
    path: "."  # Use dot (.) to represent the root directory of your GitHub repo
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
