apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bluegreen-sample
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bluegreen-sample
  template:
    metadata:
      labels:
        app: bluegreen-sample
    spec:
      containers:
      - name: bluegreen-sample
        image: nginx:1.19
        ports:
        - containerPort: 80
  strategy:
    blueGreen:
      activeService: bluegreen-active
      previewService: bluegreen-preview
      autoPromotionEnabled: false  # Manual promotion for full control

