apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-sample
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rollout-sample
  template:
    metadata:
      labels:
        app: rollout-sample
    spec:
      containers:
      - name: rollout-sample
        image: nginx:1.19
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
      - setWeight: 50
      - pause: { duration: 30 } # pause 30 seconds before 100%
